version: "3"
services:
  redis:
    image: redis:alpine
    container_name: "be_redis"
    volumes:
      - redis_data:/data
  postgres:
    container_name: "be_psql"
    image: postgres:12.0-alpine
    env_file:
      - ./docker/postgres/.env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5454:5432"
  nginx:
    image: nginx:alpine
    container_name: "be_nginx"
    ports:
      - "80:80"
    volumes:
      - ./monolith:/var/www/monolith
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
  app:
    image: be_gateway:alpine
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "be_app"
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
      - redis
volumes:
  postgres_data:
  redis_data:
  pgadmin:
